r"""makeKeyMap.py -- generate KeyMap.cs and Hotkeys.md from Hotkeys.ini.

    python makeKeyMap.py            (run from C:\FileDir)

BuildFileDir runs this before the audit, because the audit checks what it
produces. There is no command wrapper for it: it is a step in the build, not
something to run by hand.

WHAT THIS IS FOR

Hotkeys.ini is the single authored source for every command name, its key and
its description. Two things are generated from it, so the three can never
disagree:

  * KeyMap.cs  -- a table of the shipped defaults, compiled into the program.
                  It exists because the installer used to copy Hotkeys.ini
                  with the onlyifdoesntexist flag, so a machine that already
                  had FileDir never received an updated copy, and a
                  description added in a new version was never heard.
                  Hotkeys.ini in the program folder is still read first, as a
                  user override.
  * Hotkeys.md -- the hotkey reference, listing every command three ways.

Both are generated output. Do not edit them; edit Hotkeys.ini instead.

WHY THIS IS PYTHON RATHER THAN PART OF THE BUILD SCRIPT

It used to be a function inside BuildFileDir.ps1, and it broke the build. C#
source is full of double quotes, and the PowerShell that emitted it wrote
them as \" -- which is a C escape, not a PowerShell one. PowerShell escapes a
quote with a backtick. The script would not parse, so it never reached its
own logging and the build failed with a wall of parser errors and an empty
log. Generating one language's source from another is fiddly enough that it
belongs where the quoting is simple.

A detailed log is written beside this script, whatever happens.
"""

import datetime
import os
import re
import sys

c_sLogName = "makeKeyMap.log"

# The groups Hotkeys.md lists commands under, in the order they appear. A
# command falls into the first group its key matches.
c_lModifierGroups = ["Alt+Shift", "Alt+Control", "Control+Shift", "Alt",
                     "Control", "Shift", "Function keys", "Unmodified"]

pathRoot = os.path.dirname(os.path.abspath(__file__))
if "-pathRoot" in sys.argv:
    pathRoot = sys.argv[sys.argv.index("-pathRoot") + 1]
pathLog = os.path.join(os.path.dirname(os.path.abspath(__file__)), c_sLogName)
fileLog = None


def say(sMessage=""):
    print(sMessage)
    if fileLog:
        try:
            fileLog.write(sMessage + "\n")
            fileLog.flush()
        except Exception:
            pass


def startLog():
    """Open the log and record the environment, before anything can fail."""
    global fileLog
    fileLog = open(pathLog, "w", encoding="utf-8")
    say("makeKeyMap " + datetime.datetime.now().isoformat(" ", "seconds"))
    say("  script:            " + os.path.abspath(__file__))
    say("  Python:            " + sys.version.split()[0])
    say("  platform:          " + sys.platform)
    say("  working directory: " + os.getcwd())
    say("  command line:      " + " ".join([os.path.basename(sys.argv[0])] + sys.argv[1:]))
    say("  folder:            " + pathRoot)
    say()


def plural(iCount, sNoun):
    return str(iCount) + " " + sNoun + ("" if iCount == 1 else "s")


def readEntries(pathIni):
    """Read Hotkeys.ini into a list of command, key, description and value.

    Each line is  Command=Key, Description. The split is on the FIRST comma,
    which is what the program itself does, so the compiled table and the
    running program agree even for a key that contains a comma, such as
    "Comma, or Shift+Backspace".
    """
    lEntries = []
    iSkipped = 0
    with open(pathIni, encoding="utf-8-sig", errors="replace") as fileIni:
        for iLine, sLine in enumerate(fileIni, 1):
            sTrim = sLine.strip()
            if not sTrim or sTrim.startswith("[") or sTrim.startswith(";"):
                continue
            iEquals = sTrim.find("=")
            if iEquals < 1:
                iSkipped += 1
                say("  line " + str(iLine) + ": no '=' found, skipped: " + sTrim)
                continue
            sCommand = sTrim[:iEquals].strip()
            sValue = sTrim[iEquals + 1:].strip()
            iComma = sValue.find(",")
            sKey = sValue[:iComma].strip() if iComma >= 0 else ""
            sDescription = sValue[iComma + 1:].strip() if iComma >= 0 else sValue
            lEntries.append({"Command": sCommand, "Key": sKey,
                             "Description": sDescription, "Value": sValue})
    say("  read " + plural(len(lEntries), "entry").replace("entrys", "entries")
        + ", " + plural(iSkipped, "line") + " skipped")
    return lEntries


def writeKeyMap(lEntries, pathCs):
    """Write the compiled-in table of shipped defaults."""
    lOut = [
        "// KeyMap.cs -- generated by makeKeyMap.py from Hotkeys.ini.  Do not edit.",
        "//",
        "// The shipped default key and description for every FileDir command, compiled",
        "// into the program.  Hotkeys.ini in the program folder is still read first, so",
        "// a user can override any entry, but this table guarantees that a command",
        "// always has a description even on a machine whose Hotkeys.ini predates it.",
        "",
        "using System;",
        "using System.Collections.Generic;",
        "",
        "namespace Homer {",
        "",
        "public static class KeyMap {",
        "",
        '// dHotkeys maps a command name to its shipped "key, description" value, in',
        "// the same single-string form the program reads from Hotkeys.ini.",
        "public static readonly Dictionary<string, string> dHotkeys = "
        "new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) {",
    ]
    for iRow, oEntry in enumerate(lEntries, 1):
        sCommand = oEntry["Command"].replace("\\", "\\\\").replace('"', '\\"')
        sValue = oEntry["Value"].replace("\\", "\\\\").replace('"', '\\"')
        sComma = "," if iRow < len(lEntries) else ""
        lOut.append('{"' + sCommand + '", "' + sValue + '"}' + sComma)
    lOut += [
        "};",
        "",
        '// lookUp returns the shipped "key, description" value for a command, or an',
        "// empty string when the command is not in the table.  The caller decides what",
        "// to say when nothing is found, so this never invents text.",
        "public static string lookUp(string sCommand) {",
        'string sValue = "";',
        'if (sCommand == null) return "";',
        "if (dHotkeys.TryGetValue(sCommand, out sValue)) return sValue;",
        'if (dHotkeys.TryGetValue("Say " + sCommand, out sValue)) return sValue;',
        'return "";',
        "} // lookUp method",
        "",
        "} // KeyMap class",
        "",
        "} // Homer namespace",
    ]
    with open(pathCs, "w", encoding="utf-8-sig", newline="\r\n") as fileCs:
        fileCs.write("\n".join(lOut) + "\n")
    say("  wrote " + pathCs + " with " + plural(len(lEntries), "entry").replace("entrys", "entries"))


def inGroup(sGroup, sKey):
    """Whether a key belongs to one of the modifier groups in Hotkeys.md."""
    if sGroup == "Alt+Shift":
        return sKey.startswith("Alt+Shift")
    if sGroup == "Alt+Control":
        return sKey.startswith("Alt+Control")
    if sGroup == "Control+Shift":
        return sKey.startswith("Control+Shift")
    if sGroup == "Alt":
        return (sKey.startswith("Alt+") and not sKey.startswith("Alt+Shift")
                and not sKey.startswith("Alt+Control"))
    if sGroup == "Control":
        return sKey.startswith("Control+") and not sKey.startswith("Control+Shift")
    if sGroup == "Shift":
        return sKey.startswith("Shift+")
    if sGroup == "Function keys":
        return re.match(r"^F\d", sKey) is not None
    return re.match(r"^(Alt|Control|Shift|F\d)", sKey) is None


def readVersion():
    """The current version, from version.txt, or an empty string.

    Read tolerantly: a byte order mark has been in this file before, and a
    generator is no place to be strict about one.
    """
    pathVersion = os.path.join(pathRoot, "version.txt")
    if not os.path.isfile(pathVersion):
        return ""
    with open(pathVersion, "rb") as fileVersion:
        aBytes = fileVersion.read()
    if aBytes.startswith(b"\xef\xbb\xbf"):
        aBytes = aBytes[3:]
    return aBytes.decode("utf-8", errors="replace").strip().split("\n")[0].strip()


def writeHotkeys(lEntries, pathMd, sVersion):
    """Write the hotkey reference, three orderings, as lists rather than tables.

    A list reads better aloud than a table, so the same commands are given
    three ways instead of once with three sortable columns.
    """
    sToday = datetime.datetime.now().strftime("%-d %B %Y") if os.name != "nt" \
        else datetime.datetime.now().strftime("%d %B %Y").lstrip("0")
    lOut = [
        "# FileDir Hotkeys",
        "",
        "**Version " + sVersion + "**  ",
        "Copyright 2006-2026 by Jamal Mazrui  ",
        "MIT License",
        "",
        "Generated from Hotkeys.ini on " + sToday
        + ". Do not edit this file; edit Hotkeys.ini and build again.",
        "",
        "This is the complete list of FileDir commands, given three ways so you can "
        "find a command however you happen to be thinking about it. Press Control+F1 "
        "to turn on Key Describer, which says a command's name, key, and description "
        "instead of running it.",
        "",
        "## Contents",
        "",
        "- [By Command Name](#by-command-name)",
        "- [By Key](#by-key)",
        "- [By First Modifier](#by-first-modifier)",
        "",
        "## By Command Name",
        "",
        "Commands in alphabetical order.",
        "",
    ]
    for oEntry in sorted(lEntries, key=lambda o: o["Command"].lower()):
        lOut.append("- **" + oEntry["Command"] + "**, " + oEntry["Key"]
                    + " -- " + oEntry["Description"])
    lOut += ["", "## By Key", "",
             "The same commands, in alphabetical order of the key that runs them.", ""]
    for oEntry in sorted(lEntries, key=lambda o: o["Key"].lower()):
        lOut.append("- **" + oEntry["Key"] + "** -- " + oEntry["Command"]
                    + ": " + oEntry["Description"])
    lOut += ["", "## By First Modifier", "",
             "Grouped by the modifier key a command starts with, which is often the "
             "quickest way to see what a family of keys does.", ""]
    for sGroup in c_lModifierGroups:
        lInGroup = [o for o in sorted(lEntries, key=lambda o: o["Command"].lower())
                    if inGroup(sGroup, o["Key"])]
        if not lInGroup:
            continue
        lOut += ["### " + sGroup, ""]
        for oEntry in lInGroup:
            lOut.append("- **" + oEntry["Key"] + "** -- " + oEntry["Command"])
        lOut.append("")
    lOut.append("End of Document")
    with open(pathMd, "w", encoding="utf-8-sig", newline="\r\n") as fileMd:
        fileMd.write("\n".join(lOut) + "\n")
    say("  wrote " + pathMd)


def main():
    startLog()
    pathIni = os.path.join(pathRoot, "Hotkeys.ini")
    pathCs = os.path.join(pathRoot, "KeyMap.cs")
    pathMd = os.path.join(pathRoot, "Hotkeys.md")
    say("  setting IniPath: " + pathIni)
    say("  setting CsPath:  " + pathCs)
    say("  setting MdPath:  " + pathMd)
    say()

    if not os.path.isfile(pathIni):
        say("Hotkeys.ini not found at " + pathIni + ".")
        say("It is the source of every command name, key and description, so")
        say("nothing can be generated without it.")
        say("The log is at " + pathLog)
        return 1

    lEntries = readEntries(pathIni)
    if not lEntries:
        say("Hotkeys.ini contains no entries.")
        say("The log is at " + pathLog)
        return 1

    writeKeyMap(lEntries, pathCs)
    writeHotkeys(lEntries, pathMd, readVersion())
    say()
    say("KeyMap.cs and Hotkeys.md generated from "
        + plural(len(lEntries), "command") + ".")
    say("The log is at " + pathLog)
    return 0


if __name__ == "__main__":
    # An unexpected failure must reach the log too. Without this the script
    # prints a traceback to a console that scrolls away and writes nothing,
    # which is the one outcome a log exists to prevent.
    try:
        sys.exit(main())
    except SystemExit:
        raise
    except Exception:
        import traceback
        say("")
        say("makeKeyMap stopped on an unexpected error:")
        for sLine in traceback.format_exc().splitlines():
            say("  " + sLine)
        say("The log is at " + pathLog)
        sys.exit(1)
    finally:
        if fileLog:
            fileLog.close()
