# sayTutorial.ps1 -- speak the walkthrough, in two voices, into one audio file.
#
# WHAT IT MAKES
#
# Tutorial.mp3, beside this script: a narrator explaining each step, a second
# voice standing in for the screen reader, and a short click where a key is
# pressed. It says at the start that it is a simulation, because it is one.
#
# HOW, AND WHY THIS WAY
#
# Everything here is already on the machine. The voices are the Windows ones,
# through System.Speech; the joining is ffmpeg, which FileDir ships. Nothing is
# fetched, nothing is generated by a service, and the result is the same every
# time it is run -- which matters, because this is documentation.
#
# The two voices are chosen by asking Windows what it has and taking two
# different ones. With only one installed voice the reader's lines are spoken
# slower and lower than the narrator's, which is enough to tell them apart.
#
# The log is sayTutorial.log, beside this script.

$ErrorActionPreference = "Stop"
$sHere = Split-Path -Parent $MyInvocation.MyCommand.Path

# Anything unexpected goes to the log with its line and its stack, because a
# console message and an empty log is nothing to debug from.
trap {
  $sWhere = ""
  try { $sWhere = " at line " + $_.InvocationInfo.ScriptLineNumber } catch { }
  try {
    Add-Content -LiteralPath (Join-Path $sHere "sayTutorial.log") -Value (
      (Get-Date).ToString("yyyy-MM-dd HH:mm:ss") + "  UNEXPECTED: " + $_.Exception.Message + $sWhere)
    Add-Content -LiteralPath (Join-Path $sHere "sayTutorial.log") -Value ($_.ScriptStackTrace)
  } catch { }
  Write-Host "Something unexpected stopped the script. The log has it."
  exit 1
}
$sLog = Join-Path $sHere "sayTutorial.log"
# WHICH SCRIPT TO SPEAK. Named on the command line, with or without the
# extension, and Tutorial.inix when nothing is named. One tutorial to a file,
# and the audio takes the file's own name: Tutorial_Tagging.inix becomes
# Tutorial_Tagging.mp3.
$sName = "Tutorial"
foreach ($sArg in $args) {
  $sTrimmed = $sArg.Trim()
  if ($sTrimmed.Length -eq 0 -or $sTrimmed.StartsWith("-")) { continue }
  $sName = [System.IO.Path]::GetFileNameWithoutExtension($sTrimmed)
  break
}
$sSource = Join-Path $sHere ($sName + ".inix")
$sOut = Join-Path $sHere ($sName + ".mp3")
$sWork = Join-Path $env:TEMP ("sayTutorial_" + [Guid]::NewGuid().ToString("N"))

function note([string] $sText) {
  # Everything, in detail, for working out what went wrong later.
  Add-Content -LiteralPath $sLog -Value ((Get-Date).ToString("yyyy-MM-dd HH:mm:ss") + "  " + $sText)
}

function say([string] $sText) {
  # Short and plain on the screen, and the same line in the log.
  Write-Host $sText
  note $sText
}

if (Test-Path -LiteralPath $sLog) { Remove-Item -LiteralPath $sLog -Force }
note "sayTutorial starting"
note ("script: " + $MyInvocation.MyCommand.Path)
note ("PowerShell: " + $PSVersionTable.PSVersion.ToString())
note ("platform: " + [Environment]::OSVersion.VersionString)
note ("working directory: " + (Get-Location).Path)
note ("command line: " + [Environment]::CommandLine)
note ("source: " + $sSource)
note ("output: " + $sOut)
note ("work folder: " + $sWork)

if (-not (Test-Path -LiteralPath $sSource)) {
  say "Tutorial.inix is not here, so there is nothing to speak."
  exit 1
}

# ffmpeg joins the pieces. FileDir ships it, so look beside this script first.
$sFfmpeg = Join-Path $sHere "ffmpeg.exe"
if (-not (Test-Path -LiteralPath $sFfmpeg)) {
  $oFound = Get-Command ffmpeg.exe -ErrorAction SilentlyContinue
  if ($oFound) { $sFfmpeg = $oFound.Source }
}
note ("ffmpeg: " + $sFfmpeg)
if (-not $bLive -and -not (Test-Path -LiteralPath $sFfmpeg)) {
  say "ffmpeg was not found, and it is what joins the pieces together."
  say "Install the media tools, or run installMediaTools.cmd in this folder."
  exit 1
}

# LIVE: SPOKEN BY JAWS ITSELF, AND WRITTEN TO NOTHING.
#
# JAWS speaks through its own synthesizer over its own audio path, so its voice
# cannot be captured to a file without a loopback recorder this script has no
# business installing. What it CAN do is perform the walk live: the narrator
# through Windows, the screen reader's lines through JAWS, exactly as they would
# sound in use.
#
# So there are two things here, and they are different on purpose:
#   sayTutorial <name>          writes <name>.mp3, Eloquence where available
#   sayTutorial <name> -live    performs it now, through JAWS, and writes no file
$bLive = $false
foreach ($sArg in $args) { if ($sArg -eq "-live") { $bLive = $true } }
note ("live: " + $bLive)

$oJaws = $null
if ($bLive) {
  try {
    $oJaws = New-Object -ComObject FreedomSci.JawsApi
    note "JAWS COM server attached"
  }
  catch {
    note ("JAWS COM server not available: " + $_.Exception.Message)
    say "JAWS is not running, or its COM server is not available, so the live walk cannot be spoken."
    exit 1
  }
}

Add-Type -AssemblyName System.Speech
$oSpeaker = New-Object System.Speech.Synthesis.SpeechSynthesizer
$lsVoices = @($oSpeaker.GetInstalledVoices() | Where-Object { $_.Enabled } | ForEach-Object { $_.VoiceInfo.Name })
note ("voices installed: " + ($lsVoices -join ", "))
if ($lsVoices.Count -eq 0) {
  say "Windows reports 0 voices, so nothing can be spoken."
  exit 1
}
# ELOQUENCE FOR THE SCREEN READER'S LINES, WHERE THE MACHINE HAS IT.
#
# People who use JAWS have heard Eloquence for twenty years, and recognise it
# before they have understood a word. Hearing it here says "this is the screen
# reader talking" faster than any wording could. It is picked by name, from
# whatever SAPI voices Windows reports; failing that, any second voice will do,
# and failing that the one voice speaks both parts at different rates.
#
# JAWS's own Eloquence is not a SAPI voice and cannot be written to a file --
# see the -live switch below for hearing the real thing.
$sReader = ""
foreach ($sWanted in @("eloquence", "eti-eloquence", "ibmtts", "vocalizer")) {
  foreach ($sVoice in $lsVoices) {
    if ($sReader -eq "" -and $sVoice.ToLower().Contains($sWanted)) { $sReader = $sVoice }
  }
}
$sNarrator = ""
foreach ($sVoice in $lsVoices) {
  if ($sNarrator -eq "" -and $sVoice -ne $sReader) { $sNarrator = $sVoice }
}
if ($sNarrator -eq "") { $sNarrator = $lsVoices[0] }
if ($sReader -eq "") {
  note "no Eloquence-like voice found; using a second voice or a different rate"
  $sReader = if ($lsVoices.Count -gt 1 -and $lsVoices[1] -ne $sNarrator) { $lsVoices[1] } else { $lsVoices[0] }
}
note ("narrator voice: " + $sNarrator + ", reader voice: " + $sReader)
$script:sReaderVoice = $sReader

if (-not $bLive) { New-Item -ItemType Directory -Path $sWork -Force | Out-Null }
$iPiece = 0
$lsPieces = New-Object System.Collections.Generic.List[string]

# SPEED. System.Speech takes a rate from minus ten to ten, where zero is the
# pace of somebody reading to a stranger. The people this is for listen to
# synthetic speech all day and find that pace slow, so the narrator runs at
# four and the screen reader's stand-in at six -- faster still, because a
# reader's own voice is always the faster of the two.
#
# A number rather than a setting: one file that everybody hears the same way is
# worth more than a knob nobody turns.
$script:iNarratorRate = 4
$script:iReaderRate = 6

function speakLive([string] $sText, [bool] $bAsReader) {
  # Live: the reader's lines go through JAWS, the narrator's through Windows.
  # SayString returns before it has finished speaking, so the wait is worked out
  # from the length of the words -- rough, but the alternative is talking over
  # itself.
  if ($bAsReader) {
    $oJaws.SayString($sText, $true) | Out-Null
    Start-Sleep -Milliseconds ([Math]::Max(400, $sText.Length * 38))
  }
  else {
    $oSpeaker.SelectVoice($sNarrator)
    $oSpeaker.Rate = $script:iNarratorRate
    $oSpeaker.SetOutputToDefaultAudioDevice()
    $oSpeaker.Speak($sText)
  }
  note ("live [" + $(if ($bAsReader) { "JAWS" } else { "narrator" }) + "]: " + $sText)
}

function speakTo([string] $sText, [string] $sVoice, [int] $iRate) {
  if ($bLive) {
    speakLive $sText ($sVoice -eq $script:sReaderVoice)
    return
  }
  # One line of speech, written as a wave file of its own. Separate files
  # rather than one long one: a piece that fails is then one piece, and the
  # pauses between them are made by the joining rather than by the voice.
  $script:iPiece = $script:iPiece + 1
  $sFile = Join-Path $sWork ("piece_{0:D4}.wav" -f $script:iPiece)
  $oSpeaker.SelectVoice($sVoice)
  $oSpeaker.Rate = $iRate
  $oSpeaker.SetOutputToWaveFile($sFile)
  $oSpeaker.Speak($sText)
  $oSpeaker.SetOutputToNull()
  $script:lsPieces.Add($sFile)
  note ("piece " + $script:iPiece + " [" + $sVoice + " rate " + $iRate + "]: " + $sText)
}

function silenceFor([double] $dSeconds) {
  if ($bLive) { Start-Sleep -Milliseconds ([int]($dSeconds * 1000)); return }
  # A gap, made by ffmpeg rather than by the voice, so it is the same length
  # every time.
  $script:iPiece = $script:iPiece + 1
  $sFile = Join-Path $sWork ("piece_{0:D4}.wav" -f $script:iPiece)
  & $sFfmpeg -y -loglevel error -f lavfi -i anullsrc=r=22050:cl=mono -t $dSeconds $sFile 2>&1 | Out-Null
  $script:lsPieces.Add($sFile)
}

# Read the steps. A tolerant reader: a key may repeat, and repeats are kept in
# order, which is how a step holds several lines of speech.
$lsSections = New-Object System.Collections.Generic.List[hashtable]
$dNow = $null
foreach ($sRaw in (Get-Content -LiteralPath $sSource -Encoding UTF8)) {
  $sLine = $sRaw.Trim()
  if ($sLine.Length -eq 0 -or $sLine.StartsWith(";") -or $sLine.StartsWith("#")) { continue }
  if ($sLine.StartsWith("[") -and $sLine.EndsWith("]")) {
    $dNow = @{ "_name" = $sLine.Substring(1, $sLine.Length - 2).Trim().ToLower() }
    $lsSections.Add($dNow)
    continue
  }
  if ($null -eq $dNow) { continue }
  $iAt = $sLine.IndexOf("=")
  if ($iAt -lt 1) { continue }
  $sField = $sLine.Substring(0, $iAt).Trim()
  $sValue = $sLine.Substring($iAt + 1).Trim()
  if ($sValue.Length -eq 0) { continue }
  if (-not $dNow.ContainsKey($sField)) { $dNow[$sField] = New-Object System.Collections.Generic.List[string] }
  $dNow[$sField].Add($sValue)
}
note ("sections read: " + $lsSections.Count)

$dAbout = $lsSections | Where-Object { $_["_name"] -eq "about" } | Select-Object -First 1
$lsSteps = @($lsSections | Where-Object { $_["_name"] -eq "step" })
note ("steps: " + $lsSteps.Count)
if ($lsSteps.Count -eq 0) {
  say "Tutorial.inix holds 0 steps."
  exit 1
}

if ($bLive) { say ("Speaking " + $lsSteps.Count + " steps aloud now.") }
else { say ("Speaking " + $lsSteps.Count + " steps into " + [System.IO.Path]::GetFileName($sOut) + ".") }

# SAID FIRST, EVERY TIME. Anyone hearing this should know within a sentence
# that they are hearing a reconstruction rather than a recording of a session.
speakTo "Simulated walk through FileDir. Not a recording. One voice narrates; the other stands in for the screen reader." $sNarrator $script:iNarratorRate
silenceFor 0.45
if ($dAbout -and $dAbout.ContainsKey("Title")) { speakTo $dAbout["Title"][0] $sNarrator $script:iNarratorRate; silenceFor 0.35 }
if ($dAbout -and $dAbout.ContainsKey("Setup")) { speakTo $dAbout["Setup"][0] $sNarrator $script:iNarratorRate; silenceFor 0.45 }

$iStep = 0
foreach ($dStep in $lsSteps) {
  $iStep = $iStep + 1
  if ($dStep.ContainsKey("Say")) { speakTo $dStep["Say"][0] $sNarrator $script:iNarratorRate; silenceFor 0.4 }
  if ($dStep.ContainsKey("Key")) {
    speakTo ("Press " + $dStep["Key"][0]) $sNarrator $script:iNarratorRate
    silenceFor 0.35
  }
  if ($dStep.ContainsKey("Hear")) {
    foreach ($sHeard in $dStep["Hear"]) { speakTo $sHeard $sReader $script:iReaderRate }
    silenceFor 0.3
  }
}
speakTo "End of the walk." $sNarrator $script:iNarratorRate

$oSpeaker.Dispose()
note ("pieces made: " + $lsPieces.Count)

if ($bLive) {
  # Nothing was written, because nothing could be: JAWS speaks over its own
  # audio path. The walk has just been performed instead.
  try { Remove-Item -LiteralPath $sWork -Recurse -Force } catch { }
  say "The walk was spoken live. No file was written."
  exit 0
}

# ffmpeg joins them. A list file rather than a long command line: a hundred
# pieces do not fit on one.
$sList = Join-Path $sWork "pieces.txt"
$lsLines = $lsPieces | ForEach-Object { "file '" + $_.Replace("'", "'\''") + "'" }
Set-Content -LiteralPath $sList -Value $lsLines -Encoding ASCII
note ("list file: " + $sList)

& $sFfmpeg -y -loglevel error -f concat -safe 0 -i $sList -codec:a libmp3lame -q:a 4 $sOut 2>&1 | ForEach-Object { note ("ffmpeg: " + $_) }
$iExit = $LASTEXITCODE
note ("ffmpeg exit code: " + $iExit)

try { Remove-Item -LiteralPath $sWork -Recurse -Force } catch { note ("could not clear the work folder: " + $_.Exception.Message) }

if ($iExit -ne 0 -or -not (Test-Path -LiteralPath $sOut)) {
  say "The audio could not be joined. The log has what ffmpeg said."
  exit 1
}
say ("Wrote " + $sOut)
exit 0
